apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx1401
  namespace: dev1401
spec:
  containers:
  - image: kodekloud/nginx
    name: nginx
    ports:
    - containerPort: 9080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9080
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    livenessProbe:
      exec:
        command:
          - ls
          - var/www/html/file_check
      initialDelaySeconds: 10
      periodSeconds: 60


# nag edit pinalitan yung readinessProbe port tas dinagdag lang sa liveness probe, tas kubectl replace -f file.yaml --force