apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
  namespace: dev2406
spec:
  containers:
  - image: busybox
    name: secret-volume
    command:
      - sleep
      - "3600"
    volumeMounts:
      - mountPath: /etc/secret-volume
        name: secret-volume
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  nodeName: controlplane