apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
  labels:
    name: log-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /opt/volume/nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      name: "log-volume"
---
apiVersion: v1
kind: Pod
metadata:
  name: logger
spec:
  containers:
    - name: myfrontend
      image: nginx:alpine
      volumeMounts:
      - mountPath: "/var/www/nginx"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: log-claim