apiVersion: v1 
kind: Namespace
metadata:
  name: dvl1987
---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: time-config
  namespace: dvl1987
data:
  TIME_FREQ: "10"
---
apiVersion: v1 
kind: Pod
metadata:
  name: time-check
  namespace: dvl1987
spec:
  containers:
    - name: time-check
      image: busybox
      command:
        - /bin/sh
        - -c
        - while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log
      volumeMounts:
        - mountPath: /opt/time
          name: volume-mount
      env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              key: TIME_FREQ
              name: time-config
  volumes:
    - name: volume-mount
      emptyDir:
        {}